sudo: required
services:
  - docker

before_install:
  - docker build -t samjbro/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samjbro/client-test npm test
  
after_success:
# Build images
  - docker build -t samjbro/koel-nginx ./nginx
  - docker build -t samjbro/koel-client ./client
  - docker build -t samjbro/koel-api ./api
# Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to Docker Hub
  - docker push samjbro/koel-nginx
  - docker push samjbro/koel-client
  - docker push samjbro/koel-api

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: Koel
  env: Koel-env
  bucket_name: elasticbeanstalk-eu-west-2-230836431314
  bucket_path: koel
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY